<a href="https://colab.research.google.com/github/elsy-torres/invierno/blob/main/Clase_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
!pip install obspy==1.2.2

In [ ]:
!pip search obspy

In [7]:
np.random.normal(size=(5,5))

array([[ 0.34493458,  1.51307288,  1.32641515, -0.66664106, -1.17251189],
       [-1.44766128, -0.0294434 , -0.16731348, -1.44461422, -0.87788117],
       [-0.15344241,  0.53521457, -0.29713459,  0.42701594, -1.55837953],
       [-0.14090347, -0.43435812, -0.69835091, -0.76405376, -0.81321043],
       [-1.62959221,  2.60363007,  0.28322117, -0.34247835, -0.39477744]])

In [62]:
w=np.random.normal(size=(2,2))
print(w)
w2= np.random.randint(1,10,size=(2,1))
print(w2)

[[-0.19714637 -1.29849372]
 [-1.79487783 -1.15102616]]
[[9]
 [1]]


In [67]:
w*w2


array([[ -1.7743173 , -11.68644352],
       [ -1.79487783,  -1.15102616]])

In [66]:
w.dot(w2).T

array([[ -3.07281102, -17.30492667]])

In [76]:
x=np.arange(0,5)
print(x)

[0 1 2 3 4]


In [77]:
y=np.sin(x)

In [85]:
for index,val in enumerate(y):
  print('iteracion {}:valor {}'.format(index, val))

iteracion 0:valor 0.0
iteracion 1:valor 0.8414709848078965
iteracion 2:valor 0.9092974268256817
iteracion 3:valor 0.1411200080598672
iteracion 4:valor -0.7568024953079282


## Estructuras

In [16]:
tupla=(2,1,4)

In [17]:
print(tupla)

(2, 1, 4)


In [19]:
tupla.count(2)

1

In [35]:
lista=[1,2,3,5,]
print(lista)

[1, 2, 3, 5]


In [36]:
lista.append('torres')
print(lista)

[1, 2, 3, 5, 'torres']


In [33]:
lista.index(2)

1

In [37]:
lista.insert(3,4)
print(lista)

[1, 2, 3, 4, 5, 'torres']


In [38]:
diccionario={
    'nombre':'elsy',
    'apellido':'torres',
}

In [39]:
diccionario['nombre']

'elsy'

In [42]:
for key,item in diccionario.items():
  print(key+':'+ item)

nombre:elsy
apellido:torres


In [45]:
diccionario['cuatrimestre']='aprobado'

In [46]:
print(diccionario)

{'nombre': 'elsy', 'apellido': 'torres', 'semestre': 'aprobado', 'cuatrimestre': 'aprobado'}


In [48]:
diccionario.keys()

dict_keys(['nombre', 'apellido', 'semestre', 'cuatrimestre'])

In [52]:
from obspy import read

str(dato númerico)

In [41]:
diccionario.items()

dict_items([('nombre', 'elsy'), ('apellido', 'torres')])

In [ ]:
st = read('CBX0613E.PIT')