<a href="https://colab.research.google.com/github/elsy-torres/invierno/blob/main/Clase_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from obspy import read

In [11]:
search anaconda

SyntaxError: ignored

In [18]:
from pathlib import Path
for filename in Path ('/Users/Ángel/Documents/cicese2020/datos/Avanzado/1_ChiapasT').glob('*.Tacana_009'):

SyntaxError: ignored

In [3]:
!pip install obspy==1.2.2

     |████████████████████████████████| 24.7MB 178kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
  Created wheel for obspy: filename=obspy-1.2.2-cp36-cp36m-linux_x86_64.whl size=21666243 sha256=e6c43b00e5d493af6edc0d29f27ec7c9f2ea3a1aa4d55cd485cb61e7e2f38388
  Stored in directory: /root/.cache/pip/wheels/94/e0/86/44fd4cea7661f42431c8f6d030f2758ff275cccffcbe8fa2b8
Successfully built obspy


In [25]:
st= read('my20170908-044800.sac',debug_headers=True)

TypeError: ignored

In [ ]:
!pip search obspy

obspy (1.2.2)          - ObsPy - a Python framework for seismological observatories.
  INSTALLED: 1.2.2 (latest)
lcheapo-obspy (0.4.3)  - LCHEAPO data reading and plotting
obsplus (0.1.1)        - Some add-ons to obspy
obspyh5 (0.5.0)        - HDF5 write/read support for obspy
SEG2Py (0.0.4)         - SEG2Py - a Python 3 module that works around the ObsPy framework offering a flexible and easy way to visualize SEG2 seismic sections.


In [ ]:
np.random.normal(size=(5,5))

array([[ 0.34493458,  1.51307288,  1.32641515, -0.66664106, -1.17251189],
       [-1.44766128, -0.0294434 , -0.16731348, -1.44461422, -0.87788117],
       [-0.15344241,  0.53521457, -0.29713459,  0.42701594, -1.55837953],
       [-0.14090347, -0.43435812, -0.69835091, -0.76405376, -0.81321043],
       [-1.62959221,  2.60363007,  0.28322117, -0.34247835, -0.39477744]])

In [ ]:
w=np.random.normal(size=(2,2))
print(w)
w2= np.random.randint(1,10,size=(2,1))
print(w2)

[[-0.19714637 -1.29849372]
 [-1.79487783 -1.15102616]]
[[9]
 [1]]


In [ ]:
w*w2


array([[ -1.7743173 , -11.68644352],
       [ -1.79487783,  -1.15102616]])

In [ ]:
w.dot(w2).T

array([[ -3.07281102, -17.30492667]])

In [ ]:
x=np.arange(0,5)
print(x)

[0 1 2 3 4]


In [ ]:
y=np.sin(x)

In [ ]:
for index,val in enumerate(y):
  print('iteracion {}:valor {}'.format(index, val))

iteracion 0:valor 0.0
iteracion 1:valor 0.8414709848078965
iteracion 2:valor 0.9092974268256817
iteracion 3:valor 0.1411200080598672
iteracion 4:valor -0.7568024953079282


## Estructuras

In [ ]:
tupla=(2,1,4)

In [ ]:
print(tupla)

(2, 1, 4)


In [ ]:
tupla.count(2)

1

In [ ]:
lista=[1,2,3,5,]
print(lista)

[1, 2, 3, 5]


In [ ]:
lista.append('torres')
print(lista)

[1, 2, 3, 5, 'torres']


In [ ]:
lista.index(2)

1

In [ ]:
lista.insert(3,4)
print(lista)

[1, 2, 3, 4, 5, 'torres']


In [ ]:
diccionario={
    'nombre':'elsy',
    'apellido':'torres',
}

In [ ]:
diccionario['nombre']

'elsy'

In [ ]:
for key,item in diccionario.items():
  print(key+':'+ item)

nombre:elsy
apellido:torres


In [ ]:
diccionario['cuatrimestre']='aprobado'

In [ ]:
print(diccionario)

{'nombre': 'elsy', 'apellido': 'torres', 'semestre': 'aprobado', 'cuatrimestre': 'aprobado'}


In [ ]:
diccionario.keys()

dict_keys(['nombre', 'apellido', 'semestre', 'cuatrimestre'])

In [ ]:
from obspy import read

str(dato númerico)

In [ ]:
diccionario.items()

dict_items([('nombre', 'elsy'), ('apellido', 'torres')])

In [ ]:
st = read('CBX0613E.PIT')